services:
  - type: web
    name: sentinel-spam-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
